// ============================================================================
// canary_unit_web_v2.scad — EXTERIOR-ONLY web-render assembly of the CURRENT cage design (2026-10-09 v2):
// the re-railed three-row cage with the one-line stencil CANARY MONOLITH side plate
// (t1_sideplates: format = monolith, variant = stencil, layout = oneline — renders/mono_oneline_stencil_straight.png).
// NOT a part, NOT printable intent: render massing for the public website.
//
// Disclosure posture (hard rule): exterior form only.  Both END faces are plain opaque panels; the interior is an
// opaque mask block; nothing between the rails but the plates.  No wiring, boards, connectors, I/O, fins, sensor
// placement, aircraft mounting, battery brand, part numbers, dimensions or text other than the stencil CANARY.
// The compute cases sit behind the row-2 plate (t1_sideplates README) -> not visible -> not modelled.
//
// Geometry comes from the design file itself (include): frame numbers (rows 92.56 / 81.86 / 40.96 clear, 20 rails,
// 295.38 overall, face 444.5, depth 279), the monolith outline, the generated letter polygons and bolt positions,
// the chevrons, the plain-side plates with their ears and bolts, the corner / T gussets.  Render simplifications are
// marked RENDER below.
//
// grp = "all" | "body" | "dome" | "chevron" | "backer"   (render_web_v2.py exports the four colour groups)
// ============================================================================
include <../t1_sideplates/make_t1_sideplates.scad>
include <v2_vents.scad>                   // GENERATED by make_v2_vents.py: the monolith's micro-hex coarsened for line art
// ---- design selection (overrides the family file's defaults) ------------------
format = "monolith"; variant = "stencil"; layout = "oneline"; fix_mono = "ts";
view = "none"; part = "web";              // the family file emits nothing; this file selects by grp
HEX_AF = 8.0; HEX_WEB = 2.5;              // RENDER: plain-side house cell 5.0 / 1.6 coarsened (as the 2026-10-08 set) so the vents read as line art
grp = "all";

// ---- render-only numbers -----------------------------------------------------
WT = 5.0;                                 // RENDER plate thickness (design T = 5.6): keeps the hex wall edges under the renderer's 5.3 mm de-clutter
SKIN = 0.8; REB_M = 2.5; BK_T = 2.0; BK_CLR = 0.3;   // RENDER: rebate from the back round the letters to a 0.8 skin (cutout-kit trick: a 5 mm stencil
                                          // wall hides ~70 % of a 5 mm stroke at the hero angle) + a flat dark backer panel in the rebate
HEAD_D = 9.5; HEAD_H = 2.5;               // RENDER: every fastener as one small low head (design: 16 captive thumbscrews on the monolith, BHCS elsewhere)
DECK_T = 4; DECK_IN = 2; DECK_CH = 8;     // top deck plate on the top rails (as the 2026-10-08 massing; no deck wordmark — the design has none)
DOME_D = 110; DOME_C = [300, DP / 2]; PED_D = 50; PED_H = 18; PED_BASE = 90;   // dome on its pedestal, at the design's dome station (contents_ref x 300)
BAT = [45, 95, 150]; VPLATE = [6, 100, 150]; BAT_Z0 = (H_TOT - BAT[2]) / 2;    // generic V-mount-style block on the +X end face (the dome end)
END_T = 5; END_IN = 3;                    // plain end panels, recessed END_IN inside the post faces
MASK_IN = 2;

E = RAIL;
ZT = H_TOT + DECK_T;                      // deck top
LZ = lines_z()[0];                        // letter band z (from the generated layout)
LU = [min([for (L = M_LET, p = L) p[0]]), max([for (L = M_LET, p = L) p[0]])];
echo(str("WEB RENDER v2 ENVELOPE: frame ", FACE_L, " x ", DP, " x ", H_TOT, " | deck top z ", ZT, " | dome top z ", ZT + 4 + PED_H + DOME_D / 2,
         " | battery x ", FACE_L, "..", FACE_L + VPLATE[0] + BAT[0], " | overall ", FACE_L + VPLATE[0] + BAT[0], " x ", DP, " x ", ZT + 4 + PED_H + DOME_D / 2));
echo(str("WEB RENDER v2 PLATES: monolith ", W, " x ", MZ1 - MZ0, " at X0 ", X0, " (letters u ", LU, " z ", LZ, ", cap ", M_CAP, ", ", len(M_BOLTS), " heads, ",
         len(V2_CELLS), " render cells ", V2_HEX_AF, "/", V2_HEX_WEB, " in ", len(V2_FIELDS), " fields) | plain side rows ",
         [for (r = [1 : 3]) len(cells(r, "plain"))], " render cells ", HEX_AF, "/", HEX_WEB, ", ", [for (r = [1 : 3]) len(bolts(r))], " heads"));
assert(LU[0] - REB_M >= 1 && LU[1] + REB_M <= W - 1, "letter rebate runs off the plate");
assert(BK_T + 0.3 <= WT - SKIN, "backer thicker than the rebate");
assert(min([for (c = V2_CELLS, L = M_LET, p = L) norm([c[0] - p[0], c[1] - p[1]])]) >= V2_HEX_AF / sqrt(3) + REB_M + 0.5, "a render vent cell reaches the letter rebate");
assert(DOME_C[0] + DOME_D / 2 <= FACE_L - DECK_IN - DECK_CH && DOME_C[0] - DOME_D / 2 >= DECK_IN + DECK_CH, "dome overlaps the deck edge");
assert(BAT_Z0 >= E && BAT_Z0 + BAT[2] <= H_TOT - E, "battery outside the end panel");
assert(MZ1 + 0.5 <= H_TOT && MZ0 >= 0, "monolith plate runs past the frame");

C_DARK = [0.16, 0.16, 0.18]; C_LIGHT = [0.93, 0.94, 0.96]; C_WHITE = [0.98, 0.98, 0.97]; C_AMBER = [0.886, 0.604, 0.122]; C_BACK = [0.11, 0.16, 0.23];

// ---- plates (design 2D, render thickness) ---------------------------------------
module v2_hex(r_hex) rotate([0, 0, 30]) cylinder(r = r_hex, h = WT + 2, $fn = 6);
module letters2d() for (L = M_LET) polygon(L);
module mono_plate_web() difference() {                        // use frame: back on the rails at w = 0, face at w = WT
  linear_extrude(WT) mono_outline2d();
  for (c = V2_CELLS) translate([c[0], c[1], -1]) v2_hex(V2_HEX_AF / sqrt(3));
  translate([0, 0, -1]) linear_extrude(WT + 2) letters2d();                                  // CANARY through (single outlines: nothing falls out)
  translate([0, 0, -1]) linear_extrude(WT - SKIN + 1) offset(r = REB_M) letters2d();          // RENDER rebate from the back -> 0.8 skin at the letters
  translate([0, 0, WT - ACC_D]) linear_extrude(ACC_D + 1) chevrons2d(3, ACC_CLR);             // yellow chevron seats (row-3 ends)
}
module mono_backer_web() translate([0, 0, WT - SKIN - BK_T]) linear_extrude(BK_T) offset(r = REB_M - BK_CLR) letters2d();   // flat panel in the rebate
module mono_chevrons_web() translate([0, 0, WT - ACC_D]) linear_extrude(ACC_D) chevrons2d(3);
module mono_heads_web() for (b = M_BOLTS) translate([b[0], b[1], WT]) cylinder(d = HEAD_D, h = HEAD_H);
module plain_plate_web(r) difference() {
  linear_extrude(WT) outline2d(r);
  for (c = cells(r, "plain")) translate([c[0], c[1], -1]) v2_hex(HEX_R);
}
module plain_heads_web(r) for (b = bolts(r)) translate([b[0], b[1], WT]) cylinder(d = HEAD_D, h = HEAD_H);

// ---- frame, deck, ends, mask, dome, battery ---------------------------------------
module interior_mask() translate([E, E + MASK_IN, E]) cube([FACE_L - 2 * E, DP - 2 * E - 2 * MASK_IN, RAIL_Z0[3] - E]);   // flush with the posts' inner faces in X (no slit beside the posts), recessed MASK_IN behind the long faces
module end_panels() for (x = [END_IN, FACE_L - END_IN - END_T]) translate([x, E, E]) cube([END_T, DP - 2 * E, H_TOT - 2 * E]);   // plain, opaque
module plate2d_ch(w, h, ch) polygon([[ch, 0], [w - ch, 0], [w, ch], [w, h - ch], [w - ch, h], [ch, h], [0, h - ch], [0, ch]]);
module deck() translate([DECK_IN, DECK_IN, H_TOT]) linear_extrude(DECK_T) plate2d_ch(FACE_L - 2 * DECK_IN, DP - 2 * DECK_IN, DECK_CH);
module chamfered_box(s, ch) hull() for (dz = [ch, s[2] - ch]) translate([ch, ch, dz]) linear_extrude(0.01) offset(delta = ch, chamfer = true) square([s[0] - 2 * ch, s[1] - 2 * ch]);
module pedestal() translate([DOME_C[0], DOME_C[1], ZT]) {
  translate([-PED_BASE / 2, -PED_BASE / 2, 0]) chamfered_box([PED_BASE, PED_BASE, 4], 1.5);
  translate([0, 0, 4]) cylinder(d = PED_D, h = PED_H, $fn = 64);
}
module dome() translate([DOME_C[0], DOME_C[1], ZT + 4 + PED_H]) intersection() { sphere(d = DOME_D, $fn = 96); translate([-DOME_D, -DOME_D, 0]) cube(2 * DOME_D); }
module battery() {                                             // +X end face = the dome end (design: V-mount battery at the end, contents_ref)
  translate([FACE_L, DP / 2 - VPLATE[1] / 2, BAT_Z0]) chamfered_box(VPLATE, 1.5);
  translate([FACE_L + VPLATE[0], DP / 2 - BAT[1] / 2, BAT_Z0]) chamfered_box(BAT, 3);
}

module body() {
  frame_ref(); gussets_ref();
  place("wordmark") { mono_plate_web(); mono_heads_web(); }
  for (r = [1 : 3]) place("plain") { plain_plate_web(r); plain_heads_web(r); }
  interior_mask(); end_panels(); deck(); pedestal(); battery();
}

if (grp == "all" || grp == "body") color(grp == "all" ? C_DARK : C_LIGHT) body();
if (grp == "all" || grp == "dome") color(C_WHITE) dome();
if (grp == "all" || grp == "chevron") color(C_AMBER) place("wordmark") mono_chevrons_web();
if (grp == "all" || grp == "backer") color(C_BACK) place("wordmark") mono_backer_web();
