// ============================================================================
// canary_unit_web_v3.scad — EXTERIOR-ONLY web-render assembly, 2026-10-09 v3 ("black box, flat on all sides, antennas
// under clear plexiglass"): the re-railed three-row cage with the one-line stencil CANARY MONOLITH plate, now a flush
// monolithic black box with a clear acrylic top panel; the GNSS dome (low pedestal) and three generic stub antennas sit
// BENEATH the panel in the top bay (row 3).  The V-mount battery block on the +X end is the only protrusion.
// NOT a part, NOT printable intent: render massing for the public website (dark product on light paper).
//
// Disclosure posture (hard rule): exterior form only.  Under the acrylic there is a flat dark floor, the dome on its
// pedestal and the stubs — nothing else.  No wiring, boards, connectors, I/O, fins, sensor placement, aircraft mounting,
// battery brand, part numbers, dimensions or text other than the stencil CANARY.
//
// Geometry comes from the design file itself (include): frame numbers (rows 92.56 / 81.86 / 40.96 clear, 20 rails,
// 295.38 overall, face 444.5, depth 279), the monolith outline, the generated letter polygons and bolt positions, the
// chevrons, the plain-side plate outlines (with their ears) and bolts.  Render simplifications are marked RENDER.
//
// v3 vs v2 (exterior form only):
//   * the body is ONE block 444.5 x 279 x 295.38: rails, posts, both long-face plates and both end panels are flush;
//     the corner gussets are gone from the silhouette; every member / plate boundary is a 0.4 mm seam groove.
//   * the top deck + proud dome are replaced by the acrylic panel (flush with the top rails, inside them) over the
//     top bay; the dome is a LOW spherical cap (90 chord / 28 high — the v2 110 hemisphere does not fit the 55.96 bay)
//     on a 3 + 10 pedestal; three Ø10 x 36 stubs on Ø18 pucks.  Nothing protrudes above z = H_TOT.
//
// grp = "all" | "body" | "dome" | "chevron" | "backer" | "vents" | "acrylic"   (render_web_v3.py exports the groups)
// ============================================================================
include <../t1_sideplates/make_t1_sideplates.scad>
include <v2_vents.scad>                   // GENERATED by make_v2_vents.py: the monolith's micro-hex coarsened for line art
// ---- design selection (overrides the family file's defaults) ------------------
format = "monolith"; variant = "stencil"; layout = "oneline"; fix_mono = "ts";
view = "none"; part = "web";              // the family file emits nothing; this file selects by grp
HEX_AF = 8.0; HEX_WEB = 2.5;              // RENDER: plain-side house cell 5.0 / 1.6 coarsened so the vents read as line art
grp = "all";

// ---- render-only numbers -----------------------------------------------------
WT = 5.0;                                 // RENDER plate thickness (design T = 5.6) = depth of the plate features below the flush face
SKIN = 0.8; REB_M = 2.5; BK_T = 2.0; BK_CLR = 0.3;   // RENDER: letter apertures 0.8 deep over a rebate holding a flat backer panel (as v2)
MASK_IN = 2;                              // vents are blind: body behind them MASK_IN past the plate thickness
HEAD_D = 9.5; HEAD_H = 1.5;               // RENDER: every fastener as one low head (design: 16 captive thumbscrews on the monolith, BHCS elsewhere)
SEAM_W = 0.4; SEAM_D = 1.0;               // RENDER: panel / member seams as hairline grooves (the block is otherwise featureless)
ACR_T = 5.0; ACR_CLR = 0.5;               // acrylic top panel: flush with the top rails, inside them, 0.5 clearance all round
FLOOR_Z = RAIL_Z0[2] + RAIL;              // top bay floor = top of rail 3
ACR_Z0 = H_TOT - ACR_T;                   // acrylic underside
BAY_H = ACR_Z0 - FLOOR_Z;                 // clear height under the acrylic
DOME_D = 90; DOME_H = 28; DOME_C = [300, DP / 2];                    // LOW spherical cap (proportions only) at the design's dome station (contents_ref x 300)
SPH_R = (DOME_D * DOME_D / 4 + DOME_H * DOME_H) / (2 * DOME_H);     // sphere radius of the cap
PED_BASE = 80; PED_BT = 3; PED_D = 50; PED_H = 10;                    // pedestal: chamfered base plate + short column
STUB_D = 10; STUB_H = 36; STUB_PUCK = [18, 3];                       // generic short stubs on small base pucks
STUBS = [[105, DP / 2], [165, DP / 2], [225, DP / 2]];
BAT = [45, 95, 150]; VPLATE = [6, 100, 150]; BAT_Z0 = (H_TOT - BAT[2]) / 2;    // generic V-mount-style block on the +X end face (the dome end)
HEAD_CLR = 2;                             // margin between the top of anything in the bay and the acrylic underside
E = RAIL;

LZ = lines_z()[0];                        // letter band z (from the generated layout)
LU = [min([for (L = M_LET, p = L) p[0]]), max([for (L = M_LET, p = L) p[0]])];
DOME_TOP = FLOOR_Z + PED_BT + PED_H + DOME_H;
STUB_TOP = FLOOR_Z + STUB_PUCK[1] + STUB_H;
echo(str("WEB RENDER v3 ENVELOPE: block ", FACE_L, " x ", DP, " x ", H_TOT, " (flat top at z ", H_TOT, ") | battery x ", FACE_L, "..",
         FACE_L + VPLATE[0] + BAT[0], " | overall ", FACE_L + VPLATE[0] + BAT[0], " x ", DP, " x ", H_TOT));
echo(str("WEB RENDER v3 TOP BAY: floor z ", FLOOR_Z, " (top of rail 3), acrylic ", ACR_T, " thick at z ", ACR_Z0, "..", H_TOT, " -> clear ", BAY_H,
         " (row 3 clear ", ROW_H[2], " + rail ", RAIL, " - acrylic ", ACR_T, ") | dome cap ", DOME_D, " chord x ", DOME_H, " high (sphere R ", SPH_R,
         ") on ", PED_BT, " + ", PED_H, " pedestal -> top z ", DOME_TOP, ", ", ACR_Z0 - DOME_TOP, " under the acrylic | ", len(STUBS), " stubs ",
         STUB_D, " x ", STUB_H, " -> top z ", STUB_TOP, ", ", ACR_Z0 - STUB_TOP, " under"));
echo(str("WEB RENDER v3 PLATES (flush): monolith ", W, " x ", MZ1 - MZ0, " at X0 ", X0, " (letters u ", LU, " z ", LZ, ", cap ", M_CAP, ", ", len(M_BOLTS), " heads, ",
         len(V2_CELLS), " render cells ", V2_HEX_AF, "/", V2_HEX_WEB, " in ", len(V2_FIELDS), " fields) | plain side rows ",
         [for (r = [1 : 3]) len(cells(r, "plain"))], " render cells ", HEX_AF, "/", HEX_WEB, ", ", [for (r = [1 : 3]) len(bolts(r))], " heads"));
assert(LU[0] - REB_M >= 1 && LU[1] + REB_M <= W - 1, "letter rebate runs off the plate");
assert(BK_T + 0.3 <= WT - SKIN, "backer thicker than the rebate");
assert(min([for (c = V2_CELLS, L = M_LET, p = L) norm([c[0] - p[0], c[1] - p[1]])]) >= V2_HEX_AF / sqrt(3) + REB_M + 0.5, "a render vent cell reaches the letter rebate");
assert(WT + MASK_IN < E - 1, "a blind vent would break into the top bay wall");
assert(DOME_TOP + HEAD_CLR <= ACR_Z0, "dome touches the acrylic underside");
assert(STUB_TOP + HEAD_CLR <= ACR_Z0, "a stub touches the acrylic underside");
assert(DOME_C[0] - max(DOME_D, PED_BASE) / 2 >= E + ACR_CLR + 2 && DOME_C[0] + max(DOME_D, PED_BASE) / 2 <= FACE_L - E - ACR_CLR - 2 &&
       DOME_C[1] - max(DOME_D, PED_BASE) / 2 >= E + 2 && DOME_C[1] + max(DOME_D, PED_BASE) / 2 <= DP - E - 2, "dome / pedestal outside the top bay");
assert(min([for (s = STUBS) s[0]]) - STUB_PUCK[0] / 2 >= E + 2 && max([for (s = STUBS) s[0]]) + STUB_PUCK[0] / 2 <= DOME_C[0] - DOME_D / 2 - 5, "stubs outside the bay or into the dome");
assert(BAT_Z0 >= E && BAT_Z0 + BAT[2] <= H_TOT - E && DP / 2 - VPLATE[1] / 2 >= E && DP / 2 + VPLATE[1] / 2 <= DP - E, "battery outside the end panel");
assert(MZ1 + 0.5 <= H_TOT && MZ0 >= 0, "monolith plate runs past the frame");

C_DARK = [0.08, 0.1, 0.12]; C_DOME = [0.73, 0.76, 0.8]; C_AMBER = [0.886, 0.604, 0.122]; C_BACK = [0.21, 0.24, 0.29];
C_VENT = [0.04, 0.05, 0.06]; C_ACR = [0.86, 0.9, 0.94];

// ---- plate-coordinate placement: like place() but with the plate face FLUSH with the frame face -----------------------
module place_flush(sd) place(sd) translate([0, 0, -WT]) children();      // plate w = WT is the face plane; the body lies at w < WT

// ---- 2D helpers ---------------------------------------------------------------
module letters2d() for (L = M_LET) polygon(L);
module hex2d(r_hex) rotate(30) circle(r = r_hex, $fn = 6);
module ring2d(g) difference() { offset(delta = g / 2) children(); offset(delta = -g / 2) children(); }
module plate2d_ch(w, h, ch) polygon([[ch, 0], [w - ch, 0], [w, ch], [w, h - ch], [w - ch, h], [ch, h], [0, h - ch], [0, ch]]);
module chamfered_box(s, ch) hull() for (dz = [ch, s[2] - ch]) translate([ch, ch, dz]) linear_extrude(0.01) offset(delta = ch, chamfer = true) square([s[0] - 2 * ch, s[1] - 2 * ch]);

// ---- plate feature CUTS, in plate coords (face at w = WT, body below it) -----------------------------------------------
module mono_cuts() {
  for (c = V2_CELLS) translate([c[0], c[1], -MASK_IN]) linear_extrude(WT + MASK_IN + 1) hex2d(V2_HEX_AF / sqrt(3));   // blind vents
  translate([0, 0, -MASK_IN]) linear_extrude(WT + MASK_IN + 1) letters2d();                                           // CANARY apertures (single outlines: nothing falls out)
  translate([0, 0, -MASK_IN]) linear_extrude(WT - SKIN + MASK_IN) offset(r = REB_M) letters2d();                      // rebate behind the 0.8 skin (holds the backer)
  translate([0, 0, WT - ACC_D]) linear_extrude(ACC_D + 1) chevrons2d(3, ACC_CLR);                                      // chevron seats (row-3 ends)
}
module plain_cuts(r) for (c = cells(r, "plain")) translate([c[0], c[1], -MASK_IN]) linear_extrude(WT + MASK_IN + 1) hex2d(HEX_R);
module mono_vent_backs() for (c = V2_CELLS) translate([c[0], c[1], -MASK_IN]) linear_extrude(0.6) hex2d(V2_HEX_AF / sqrt(3) - 0.1);   // darker vent floors (own colour group)
module plain_vent_backs(r) for (c = cells(r, "plain")) translate([c[0], c[1], -MASK_IN]) linear_extrude(0.6) hex2d(HEX_R - 0.1);
module mono_heads() for (b = M_BOLTS) translate([b[0], b[1], WT]) cylinder(d = HEAD_D, h = HEAD_H);
module plain_heads(r) for (b = bolts(r)) translate([b[0], b[1], WT]) cylinder(d = HEAD_D, h = HEAD_H);
module mono_backer() translate([0, 0, WT - SKIN - BK_T]) linear_extrude(BK_T) offset(r = REB_M - BK_CLR) letters2d();   // flat panel in the rebate
module mono_chevrons() translate([0, 0, WT - ACC_D]) linear_extrude(ACC_D) chevrons2d(3);

// ---- seam grooves (2D in face coords, cut SEAM_D into the face) -------------------------------------------------------
// members: posts + rails as the frame_ref() lays them; a plate covers the member seams under it and adds its own outline seam.
module clip2d(w, h) intersection() { children(); translate([0.5, 0.5]) square([w - 1, h - 1]); }   // never notch the block's outer edges
module long_members2d() {
  for (x = [0, FACE_L - E]) translate([x, 0]) ring2d(SEAM_W) square([E, H_TOT]);
  for (z = RAIL_Z0) translate([E, z]) ring2d(SEAM_W) square([FACE_L - 2 * E, E]);
}
module long_plates2d(sd, d = 0) if (sd == "wordmark") translate([X0, 0]) offset(delta = d) mono_outline2d();
                                else for (r = [1 : 3]) translate([FACE_L - X0, 0]) mirror([1, 0]) offset(delta = d) outline2d(r);   // place("plain") mirrors u
module long_seams2d(sd) clip2d(FACE_L, H_TOT) {
  difference() { long_members2d(); long_plates2d(sd, SEAM_W / 2 + 0.01); }
  if (sd == "wordmark") translate([X0, 0]) ring2d(SEAM_W) mono_outline2d();
  else for (r = [1 : 3]) translate([FACE_L - X0, 0]) mirror([1, 0]) ring2d(SEAM_W) outline2d(r);
}
module end_seams2d() clip2d(DP, H_TOT) {                                   // (y, z): posts, bottom / top cross rails, the plain end panel between them
  for (y = [0, DP - E]) translate([y, 0]) ring2d(SEAM_W) square([E, H_TOT]);
  for (z = [0, H_TOT - E]) translate([E, z]) ring2d(SEAM_W) square([DP - 2 * E, E]);
  translate([E, E]) ring2d(SEAM_W) square([DP - 2 * E, H_TOT - 2 * E]);
}
module top_seams2d() clip2d(FACE_L, DP) difference() {                     // (x, y): posts + rails round the bay (the bay edge itself is a real edge)
  union() {
    for (x = [0, FACE_L - E], y = [0, DP - E]) translate([x, y]) ring2d(SEAM_W) square([E, E]);
    for (y = [0, DP - E]) translate([E, y]) ring2d(SEAM_W) square([FACE_L - 2 * E, E]);
    for (x = [0, FACE_L - E]) translate([x, E]) ring2d(SEAM_W) square([E, DP - 2 * E]);
  }
  translate([E - 1, E - 1]) square([FACE_L - 2 * E + 2, DP - 2 * E + 2]);
}
module seams() {
  rotate([90, 0, 0]) translate([0, 0, -SEAM_D]) linear_extrude(SEAM_D + 1) long_seams2d("wordmark");                       // y = 0 face
  translate([0, DP, 0]) mirror([0, 1, 0]) rotate([90, 0, 0]) translate([0, 0, -SEAM_D]) linear_extrude(SEAM_D + 1) long_seams2d("plain");   // y = DP face
  rotate([90, 0, 90]) translate([0, 0, -1]) linear_extrude(SEAM_D + 1) end_seams2d();                                        // x = 0 face
  translate([FACE_L, 0, 0]) mirror([1, 0, 0]) rotate([90, 0, 90]) translate([0, 0, -1]) linear_extrude(SEAM_D + 1) end_seams2d();   // x = FACE_L face
  translate([0, 0, H_TOT - SEAM_D]) linear_extrude(SEAM_D + 1) top_seams2d();                                                 // top rails
}

// ---- massing ------------------------------------------------------------------
module battery() {                                             // +X end face = the dome end (design: V-mount battery at the end, contents_ref)
  translate([FACE_L, DP / 2 - VPLATE[1] / 2, BAT_Z0]) chamfered_box(VPLATE, 1.5);
  translate([FACE_L + VPLATE[0], DP / 2 - BAT[1] / 2, BAT_Z0]) chamfered_box(BAT, 3);
}
module pedestal() translate([DOME_C[0], DOME_C[1], FLOOR_Z]) {
  translate([-PED_BASE / 2, -PED_BASE / 2, 0]) chamfered_box([PED_BASE, PED_BASE, PED_BT], 1.0);
  translate([0, 0, PED_BT]) cylinder(d = PED_D, h = PED_H, $fn = 64);
}
module stubs() for (s = STUBS) translate([s[0], s[1], FLOOR_Z]) {
  cylinder(d = STUB_PUCK[0], h = STUB_PUCK[1], $fn = 48);
  translate([0, 0, STUB_PUCK[1]]) cylinder(d = STUB_D, h = STUB_H - STUB_D / 2, $fn = 48);
  translate([0, 0, STUB_PUCK[1] + STUB_H - STUB_D / 2]) sphere(d = STUB_D, $fn = 48);
}
module dome() translate([DOME_C[0], DOME_C[1], FLOOR_Z + PED_BT + PED_H - (SPH_R - DOME_H)]) intersection() {
  sphere(r = SPH_R, $fn = 96);
  translate([-SPH_R, -SPH_R, SPH_R - DOME_H]) cube([2 * SPH_R, 2 * SPH_R, DOME_H + 1]);
}
module acrylic() translate([E + ACR_CLR, E + ACR_CLR, ACR_Z0]) cube([FACE_L - 2 * E - 2 * ACR_CLR, DP - 2 * E - 2 * ACR_CLR, ACR_T]);

module body() {
  difference() {
    union() { cube([FACE_L, DP, H_TOT]); battery(); }
    translate([E, E, FLOOR_Z]) cube([FACE_L - 2 * E, DP - 2 * E, H_TOT]);        // the top bay (open to the acrylic)
    place_flush("wordmark") mono_cuts();
    for (r = [1 : 3]) place_flush("plain") plain_cuts(r);
    seams();
  }
  place_flush("wordmark") mono_heads();
  for (r = [1 : 3]) place_flush("plain") plain_heads(r);
  pedestal(); stubs();
}

if (grp == "all" || grp == "body") color(C_DARK) body();
if (grp == "all" || grp == "dome") color(C_DOME) dome();
if (grp == "all" || grp == "chevron") color(C_AMBER) place_flush("wordmark") mono_chevrons();
if (grp == "all" || grp == "backer") color(C_BACK) place_flush("wordmark") mono_backer();
if (grp == "all" || grp == "vents") color(C_VENT) { place_flush("wordmark") mono_vent_backs(); for (r = [1 : 3]) place_flush("plain") plain_vent_backs(r); }
if (grp == "all" || grp == "acrylic") color(C_ACR, 0.35) acrylic();
