#!/usr/bin/env python3
"""
make_v2_vents.py — coarsen the monolith plate's micro-hex vent fields for the web line-art renders.

The design (t1_sideplates, format=monolith / stencil / oneline) lays 698 micro-hex cells (3.2 AF / 1.2 web) in
`wm_layout_oneline.scad` (L1_CELLS_ST).  At web size (2400 px across ~560 mm of projected unit) a 3.2 mm cell is
~12 px wide and turns to mush under a 1.6 px line, so — exactly as the 2026-10-08 set coarsened the house 5.0/1.6 cell
to 8.0/2.5 — this script re-lays each vent FIELD (the bounding box of each connected cluster of design cells) with a
coarser cell, keeping the design's rules: every cell inside its field's footprint, >= 4 mm web to every stencil letter.

    python3 make_v2_vents.py            -> writes v2_vents.scad next to this file (V2_HEX_AF, V2_HEX_WEB, V2_FIELDS, V2_CELLS)

Render-only output: nothing here is a part.
"""
from __future__ import annotations
import math, re
from pathlib import Path

HERE = Path(__file__).resolve().parent
LAYOUT = HERE.parent / "t1_sideplates" / "wm_layout_oneline.scad"
OUT = HERE / "v2_vents.scad"

FINE_AF, FINE_WEB = 3.2, 1.2                    # design micro-hex
AF, WEB = 5.6, 2.0                              # render cell (pitch 7.6 vs 4.4: ~3x fewer cells, still finer than the plain side's 8.0)
LETTER_WEB = 4.0                                # design rule: >= 4 web letter -> cell
R = AF / math.sqrt(3)                           # circumradius (pointy-top hexagon, rotate(30) in the SCAD)


def read_var(text: str, name: str):
    m = re.search(rf"^{name}\s*=\s*(.*?);", text, re.M | re.S)
    if not m:
        raise SystemExit(f"{name} not found in {LAYOUT}")
    return eval(m.group(1), {"__builtins__": {}})   # numeric nested lists only (generated file)


def clusters(cells, pitch):
    """Connected components of the fine lattice (neighbours within 1.15 x pitch)."""
    n = len(cells); lab = [-1] * n; k = 0
    r2 = (1.15 * pitch) ** 2
    for i in range(n):
        if lab[i] >= 0:
            continue
        stack = [i]; lab[i] = k
        while stack:
            a = stack.pop()
            ax, ay = cells[a]
            for b in range(n):
                if lab[b] < 0 and (cells[b][0] - ax) ** 2 + (cells[b][1] - ay) ** 2 <= r2:
                    lab[b] = k; stack.append(b)
        k += 1
    groups = [[cells[i] for i in range(n) if lab[i] == j] for j in range(k)]
    return groups


def seg_dist(px, py, ax, ay, bx, by):
    dx, dy = bx - ax, by - ay
    L2 = dx * dx + dy * dy
    t = 0.0 if L2 == 0 else max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / L2))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def inside(px, py, poly):
    c = False
    for i in range(len(poly)):
        ax, ay = poly[i]; bx, by = poly[i - 1]
        if (ay > py) != (by > py) and px < (bx - ax) * (py - ay) / (by - ay) + ax:
            c = not c
    return c


def poly_dist(px, py, poly):
    if inside(px, py, poly):
        return 0.0
    return min(seg_dist(px, py, *poly[i], *poly[i - 1]) for i in range(len(poly)))


def main():
    text = LAYOUT.read_text()
    fine = read_var(text, "L1_CELLS_ST")
    letters = read_var(text, "L1_LETTERS")
    fine_pitch = FINE_AF + FINE_WEB
    fine_r = FINE_AF / math.sqrt(3)
    fields = []
    for g in clusters(fine, fine_pitch):
        us = [c[0] for c in g]; vs = [c[1] for c in g]
        # field footprint = the fine cells' outer extents (centres +/- circumradius)
        fields.append([min(us) - fine_r, max(us) + fine_r, min(vs) - fine_r, max(vs) + fine_r, len(g)])
    fields.sort(key=lambda f: (-f[2], f[0]))
    px = AF + WEB; py = px * math.sqrt(3) / 2
    cells = []
    per_field = []
    for u0, u1, v0, v1, nfine in fields:
        nu = int(math.floor((u1 - u0 - 2 * R) / px)) + 1
        nv = int(math.floor((v1 - v0 - 2 * R) / py)) + 1
        uu0 = (u0 + u1) / 2 - (nu - 1) * px / 2
        vv0 = (v0 + v1) / 2 - (nv - 1) * py / 2
        n0 = len(cells)
        for j in range(nv):
            for i in range(nu):
                u = uu0 + i * px + (px / 2 if j % 2 else 0)
                v = vv0 + j * py
                if u - R < u0 - 0.05 or u + R > u1 + 0.05:
                    continue
                if min(poly_dist(u, v, L) for L in letters) < LETTER_WEB + R:
                    continue
                cells.append((round(u, 2), round(v, 2)))
        per_field.append(len(cells) - n0)
    area = len(cells) * (math.sqrt(3) / 2) * AF * AF / 100
    lines = [f"// GENERATED by make_v2_vents.py from {LAYOUT.name} — do not edit.  Render-only coarsening of the monolith's",
             f"// micro-hex ({FINE_AF} AF / {FINE_WEB} web, {len(fine)} cells) to {AF} AF / {WEB} web, {len(cells)} cells in {len(fields)} fields;",
             f"// every cell inside its design field's footprint and >= {LETTER_WEB} mm from every stencil letter.  Open area {area:.1f} cm2 (render only).",
             f"V2_HEX_AF = {AF}; V2_HEX_WEB = {WEB};",
             "V2_FIELDS = [" + ", ".join(f"[{u0:.2f}, {u1:.2f}, {v0:.2f}, {v1:.2f}]" for u0, u1, v0, v1, _ in fields) + "];   // [u0, u1, v0, v1] per field",
             "V2_CELLS = [" + ", ".join(f"[{u}, {v}]" for u, v in cells) + "];"]
    OUT.write_text("\n".join(lines) + "\n")
    for (u0, u1, v0, v1, nfine), n in zip(fields, per_field):
        print(f"field u {u0:6.1f}..{u1:6.1f}  v {v0:6.1f}..{v1:6.1f}  fine {nfine:3d} -> coarse {n}")
    print(f"wrote {OUT}: {len(cells)} cells, {area:.1f} cm2")


if __name__ == "__main__":
    main()
