// GENERATED by make_cutout_layout.py
CO_W = 304.8; CO_H = 80.8; CO_RIM = 5.0; CO_BOSS = [[20, 9.0], [291.8, 9.0], [20, 71.8], [291.8, 71.8]]; CO_BOSS_D = 14.0;
CO_PEGS = [[152.4, 7.0], [152.4, 73.8]]; CO_FHEX = [5.0, 1.6]; CO_BHEX = [1.6, 0.8]; CO_FIN = [30.15, 119.15];
