// ============================================================================
// CANARY T1 CAGE — LONG-FACE SIDE PLATES                    (t1_sideplates family, 2026-10-07)
// Owner: new side plates "that elevate the look of the Cage" on the re-railed frame.
//
// FRAME (owner 2026-10-07, MEAS): the long face has THREE rows / FOUR rails.  "first row 92.56 mm in
// height, second row 81.86, third row 40.96" — read BOTTOM-UP as clear openings between rail faces:
//   row 1 = deck -> rail 2  (hub, printed node, MTi)        92.56
//   row 2 = rail 2 -> rail 3 (the case / rod bay)            81.86
//   row 3 = rail 3 -> top rail (short top bay)               40.96
// Photo 48 centre-to-centre ratios 316 : 284 : 156 px = 1 : 0.90 : 0.49 vs 112.56 : 101.86 : 60.96 =
// 1 : 0.90 : 0.54 -> bottom-up is the only order that fits.  Face length 444.5 kept (photo scale CONFIRM).
//
// FASTENING = t1_panels rev B: plates sit flat on the rail faces BETWEEN the corner gussets (plain
// chamfered ends); every SHARED rail is split on its slot centreline, each plate reaching over with
// castellated ears into the other's notches; M5 into 14122 T-nuts on the slot centrelines.
// EAR PATTERN (consistent on every shared rail): the LOWER plate owns set A (up-ears), the UPPER plate
// owns set B (down-ears) -> row 1: A up | row 2: B down + A up | row 3: B down.  Deck and top rails are not
// shared: plain bolts at set A.  Every plate is removable on its own 4 bolts per half.
//   side = "wordmark" (photo-48 side: CANARY on row 2, yellow snap-in chevrons, row 1 on captive thumbscrews)
//        | "plain"    (other side: vents only, flush BHCS everywhere)
//   row  = 1 | 2 | 3 ;  half = "L" | "R" | "full" (row 3 only: one piece, 45 deg on the bed)
//   part = "plate" | "splice" | "spline" | "chevron"        view = "none" | "cage_wm" | "cage_plain" | "cage34" | "exploded"
// Each plate (304.8) is wider than the bed: two halves on the rev B centreline seam — loose spline in grooves
// + one rear splice bar per plate on 4 x M3 heat-sets.  PRINT: FACE DOWN (bed finish on the face; engraving,
// chevron seats, counterbores and thumbscrew seats are shallow bed-face recesses; hex through).
// Material: ASA flight (black body, yellow chevrons), PLA fit-check.
// ============================================================================
use <../t1_panels/make_t1_panels.scad>     // house wordmark2d() (real vector, 92 wide) + stroke()
include <wm_layout_twoline.scad>          // GENERATED by make_wordmark_layout.py from brand/canary-wordmark.svg (letters, seam, cells, pegs)
include <wm_layout_oneline.scad>
include <cutout_common.scad>              // GENERATED by make_cutout_layout.py
include <cutout_layout_native.scad>
include <cutout_layout_condensed.scad>
side = "wordmark";
format = "rows";        // "rows" (three plates per side) | "monolith" (WORDMARK side only: one plate deck -> top) | "cutout" (WORDMARK side row 2: black CANARY cut-out plate + yellow backer INSIDE the bay; rows 1/3 cover rails 2/3 fully)
lettering = "condensed"; // cutout: "condensed" (DIN Condensed Bold, off the case fins, cap 42.7) | "native" (house wordmark, cap 30.2)
co_fix = "bhcs";        // cutout screws: "bhcs" (M4 + washer) | "ts" (captive M4 thumbscrews)
$co = false;
variant = "stencil";    // monolith: "stencil" (letters cut through as vents) | "applique" (yellow letters standing on pegs over a micro-hex plate)
layout = "twoline";     // monolith: "twoline" (CAN over ARY, cap 58.8 — recommended) | "oneline" (CANARY, seam in the N|A gap, cap 30)
fix_mono = "ts";        // monolith fasteners: "ts" captive thumbscrews (it is the access door for the hub / MTi row) | "bhcs"
let_i = 0;              // part = "letter": which letter (0..5)
row = 2;
half = "L";
part = "plate";
view = "none";
$fn = 40;

// ---------------------------------------------------------------- frame (owner 2026-10-07)
ROW_H = [92.56, 81.86, 40.96];      // MEAS clear openings, bottom-up (order: assumption, see header)
RAIL = 20;
RAIL_Z0 = [0, RAIL + ROW_H[0], 2 * RAIL + ROW_H[0] + ROW_H[1], 3 * RAIL + ROW_H[0] + ROW_H[1] + ROW_H[2]];   // rail bottoms
SLOT = [for (z = RAIL_Z0) z + RAIL / 2];
H_TOT = RAIL_Z0[3] + RAIL;
FACE_L = 444.5;                     // EST (17.5 in); photo-48 scale disagrees (CONFIRM by tape)
DP = 279;                           // EST depth (end face)
GUS_RL = 62;                        // gusset rail leg (photo 39/48 EST)
W = 304.8;                          // 12 in class, between the corner gussets
X0 = (FACE_L - W) / 2;
// ---------------------------------------------------------------- plate (house numbers, rev B)
T = 5.6; M5B = 5.4; CB_D = 10.4; CB_H = 3.2; TS_SEAT = [11.6, 1.0];
M3B = 3.4; INS3_D = 4.4; INS3_DEP = 4.0; ACC_D = 1.6; ACC_CLR = 0.15;
EAR_W = 20; EAR_OV = 18.5; EAR_CLR = 1;            // ears 20 wide: >= 4 wall round a 10.4 counterbore
SET_A = [32, 100]; SET_B = [66, 134];             // per half, from the plate's outer end (mirrored)
CORNER = 6; SEAM_KO = 18; WIN_U0 = 22; WIN_M = 2.0; NOTCH_KO = 0.4;
SPL = [1.6, 2.2]; SPLICE_HW = 16; SPLICE_T = 4; INS_X = 8;
HEX_AF = 5.0; HEX_WEB = 1.6; HEX_R = HEX_AF / sqrt(3);    // house cell
WM_ROW = 2; WM_POS = "right";                               // "right" = in the right half of row 2 (off the case fins, no seam crossing) | "centre" (across the seam, in the N|A gap)
WM_W = WM_POS == "right" ? 112 : 128; WM_K = WM_W / 92;     // wordmark scaled from the house 92 mm vector
WM_U = WM_POS == "right" ? (W / 2 + SEAM_KO + W - WIN_U0) / 2 : W / 2;
WM_GAP = 0.55 * WM_K;                                       // N|A letter gap centre (SVG glyph extents: gap -0.72..1.83 at 92 wide) -> the seam runs in the gap
FIN_U = [30, 119];                                          // EST photo 48: case fins behind the LEFT half of row 2 (I/O end left)

function mir(xs) = concat(xs, [for (x = xs) W - x]);
function vb(r) = ($co && r == 3) ? RAIL_Z0[2] : r == 1 ? 0 : SLOT[r - 1];                 // $co: cutout set — rows 1/3 cover rails 2/3 fully, no ears
function vt(r) = ($co && r == 1) ? RAIL_Z0[1] + RAIL : r == 3 ? H_TOT : SLOT[r];
function bay(r) = [RAIL_Z0[r - 1] + RAIL, RAIL_Z0[r]];
function upears(r) = $co ? [] : r < 3 ? mir(SET_A) : [];
function downears(r) = $co ? [] : r > 1 ? mir(SET_B) : [];
function topnotch(r) = $co ? [] : r < 3 ? mir(SET_B) : [];
function botnotch(r) = $co ? [] : r > 1 ? mir(SET_A) : [];
function bolts(r) = concat([for (x = (r == 1 ? mir(SET_A) : mir(SET_B))) [x, r == 1 ? SLOT[0] : SLOT[r - 1]]],
                           [for (x = mir(SET_A)) [x, r == 3 ? SLOT[3] : SLOT[r]]]);
function thumbs(r, s) = s == "wordmark" && r == 1;
function wm_v() = (bay(WM_ROW)[0] + bay(WM_ROW)[1]) / 2;
// keep-outs (rects [u0, u1, v0, v1]) for the hex windows
function kos(r, s) = concat(
  [[W / 2 - SEAM_KO, W / 2 + SEAM_KO, -999, 999]],
  [for (x = topnotch(r)) [x - EAR_W / 2 - EAR_CLR - NOTCH_KO, x + EAR_W / 2 + EAR_CLR + NOTCH_KO, vt(r) - EAR_OV - EAR_CLR - NOTCH_KO, 999]],
  [for (x = botnotch(r)) [x - EAR_W / 2 - EAR_CLR - NOTCH_KO, x + EAR_W / 2 + EAR_CLR + NOTCH_KO, -999, vb(r) + EAR_OV + EAR_CLR + NOTCH_KO]],
  s == "wordmark" && r == WM_ROW ? [[WM_U - WM_W / 2 - 5, WM_U + WM_W / 2 + 5, wm_v() - 7 * WM_K - 4, wm_v() + 7 * WM_K + 4]] : []);
function outside_ko(c, ks, m) = len([for (k = ks) if (c[0] > k[0] - m && c[0] < k[1] + m && c[1] > k[2] - m && c[1] < k[3] + m) 1]) == 0;
function cells(r, s) = let(b = bay(r), u0 = WIN_U0, u1 = W - WIN_U0, v0 = b[0] + WIN_M, v1 = b[1] - WIN_M,
    px = HEX_AF + HEX_WEB, py = px * sqrt(3) / 2, m = HEX_R + HEX_WEB / 2, ks = kos(r, s))
  [for (j = [0 : floor((v1 - v0) / py)], i = [0 : floor((u1 - u0) / px) + 1])
     let(c = [u0 + m + i * px + (j % 2) * px / 2, v0 + m + j * py])
     if (c[0] <= u1 - m && c[1] <= v1 - m && outside_ko(c, ks, m)) c];
function cm2(n) = n * (sqrt(3) / 2) * HEX_AF * HEX_AF / 100;

// ---------------------------------------------------------------- 2D
module outline2d(r) difference() {
  union() {
    offset(delta = 0) polygon([[CORNER, vb(r)], [W - CORNER, vb(r)], [W, vb(r) + CORNER], [W, vt(r) - CORNER], [W - CORNER, vt(r)], [CORNER, vt(r)], [0, vt(r) - CORNER], [0, vb(r) + CORNER]]);
    for (x = upears(r)) translate([x - EAR_W / 2, vt(r) - 1]) offset(r = 2) offset(delta = -2) square([EAR_W, EAR_OV + 1]);
    for (x = downears(r)) translate([x - EAR_W / 2, vb(r) - EAR_OV]) offset(r = 2) offset(delta = -2) square([EAR_W, EAR_OV + 1]);
  }
  for (x = topnotch(r)) translate([x - EAR_W / 2 - EAR_CLR, vt(r) - EAR_OV - EAR_CLR]) square([EAR_W + 2 * EAR_CLR, EAR_OV + EAR_CLR + 1]);
  for (x = botnotch(r)) translate([x - EAR_W / 2 - EAR_CLR, vb(r) - 1]) square([EAR_W + 2 * EAR_CLR, EAR_OV + EAR_CLR + 1]);
}
function chev_pts(r) = let(b = bay(r), c = (b[0] + b[1]) / 2, hh = (b[1] - b[0]) / 2 - 7, k = min(8, hh / 2))
  [[15, c + hh], [7, c + hh - k], [7, c - hh + k], [15, c - hh]];
module chevrons2d(r, d = 0) for (m = [0, 1]) translate([m * W, 0]) mirror([m, 0]) offset(delta = d) stroke(chev_pts(r), 5);
module wordmark_sp() translate([WM_U - (WM_POS == "centre" ? WM_GAP : 0), wm_v() - 11.57 * WM_K]) scale(WM_K) wordmark2d();

// ---------------------------------------------------------------- 3D (use frame: back on the rails at w = 0, face at w = T)
module plate_full(r, s) difference() {
  linear_extrude(T) outline2d(r);
  for (c = cells(r, s)) translate([c[0], c[1], -1]) rotate([0, 0, 30]) cylinder(r = HEX_R, h = T + 2, $fn = 6);
  for (b = bolts(r)) translate([b[0], b[1], 0]) {
    translate([0, 0, -1]) cylinder(d = M5B, h = T + 2);
    if (thumbs(r, s)) translate([0, 0, T - TS_SEAT[1]]) cylinder(d = TS_SEAT[0], h = 2);
    else translate([0, 0, T - CB_H]) cylinder(d = CB_D, h = CB_H + 1);
  }
  if (s == "wordmark" && !$co) {
    translate([0, 0, T - ACC_D]) linear_extrude(ACC_D + 1) chevrons2d(r, ACC_CLR);            // yellow chevron seats
    if (r == WM_ROW) translate([0, 0, T - 1.2]) linear_extrude(2) wordmark_sp();              // CANARY, engraved 1.2
  }
  // seam: loose-spline groove (both halves) + M3 heat-sets for the rear splice bar
  translate([W / 2 - SPL[1], vb(r) + 6, T / 2 - SPL[0] / 2 - 0.1]) cube([2 * SPL[1], vt(r) - vb(r) - 12, SPL[0] + 0.2]);
  for (p = splice_ins(r)) translate([p[0], p[1], -0.01]) cylinder(d = INS3_D, h = INS3_DEP);
}
function splice_ins(r) = let(b = bay(r), c = (b[0] + b[1]) / 2, dv = (b[1] - b[0]) / 2 - 10) [for (s = [-1, 1], t = [-1, 1]) [W / 2 + s * INS_X, c + t * dv]];
module splice_bar(r) let(b = bay(r)) difference() {
  translate([W / 2 - SPLICE_HW, b[0] + 3, -SPLICE_T]) cube([2 * SPLICE_HW, b[1] - b[0] - 6, SPLICE_T]);
  for (p = splice_ins(r)) translate([p[0], p[1], -SPLICE_T - 1]) { cylinder(d = M3B, h = SPLICE_T + 2); cylinder(d = 6.2, h = 2.5); }
}
module spline(r) cube([2 * SPL[1] - 0.4, vt(r) - vb(r) - 13, SPL[0]]);
module chevron_part(r) linear_extrude(ACC_D) stroke(chev_pts(r), 5);
module half_of(r, s, h) intersection() {
  plate_full(r, s);
  translate([h == "L" ? -1 : W / 2, vb(r) - EAR_OV - 2, -1]) cube([W / 2 + 1, vt(r) - vb(r) + 2 * EAR_OV + 4, T + 2]);
}
// ---------------------------------------------------------------- checks
function fin_cells(r, s) = len([for (c = cells(r, s)) if (c[0] >= FIN_U[0] && c[0] <= FIN_U[1]) 1]);
for (s = ["wordmark", "plain"], r = [1, 2, 3])
  echo(str("OPEN ", s, " row ", r, ": ", len(cells(r, s)), " cells = ", round(cm2(len(cells(r, s))) * 10) / 10, " cm2 per plate",
           r == 2 ? str(" | over the case fins (u ", FIN_U, ", one half) ", round(cm2(fin_cells(r, s)) * 10) / 10, " cm2 (R4.2 >= 32: ", cm2(fin_cells(r, s)) >= 32 ? "MET" : "NOT MET", ")") : ""));
echo(str("FRAME: rows ", ROW_H, " bottom-up -> slot z ", SLOT, ", height ", H_TOT, "; plate ", W, " x X0 ", X0, " (", X0 - GUS_RL, " clear of the gusset legs)"));
echo(str("EARS: shared rails split on the slot line; lower plate owns set A ", mir(SET_A), ", upper plate set B ", mir(SET_B), "; ears ", EAR_W, " x ", EAR_OV));
maxspan = side == "wordmark" && row == 1 ? TS_SEAT[0] : CB_D;
echo(str("MAXSPAN=", part == "co_front" || part == "co_backer" ? CF_MAXSPAN : maxspan));
assert(EAR_W / 2 - CB_D / 2 >= 2.4 && EAR_W / 2 - TS_SEAT[0] / 2 >= 2.4, "ear wall at the fastener");
assert(min([for (a = SET_A, b = SET_B) abs(a - b)]) - EAR_W / 2 - (EAR_W / 2 + EAR_CLR) >= 10, "ear / notch web < 10");
assert(W / 2 - max(SET_B) - (EAR_W / 2 + EAR_CLR) >= 4, "notch too close to the seam");
assert(min(SET_A) - EAR_W / 2 - EAR_CLR >= 17.5 + 2, "notch runs into the chevron zone");
assert(X0 - GUS_RL >= 3, "plate end hits the gusset legs");
assert(T - INS3_DEP >= 1.5 && T - 1.2 - (T / 2 + SPL[0] / 2) >= 0.5, "insert / engraving / groove skins");
assert(SEAM_KO >= INS_X + INS3_D / 2 + 1.6 + HEX_R, "splice inserts inside the hex field");
// ---------------------------------------------------------------- cage scene (photo 48 = the WORDMARK side at y = 0)
module place(sd) if (sd == "wordmark") translate([X0, 0, 0]) rotate([90, 0, 0]) children();
                 else translate([FACE_L - X0, DP, 0]) rotate([90, 0, 180]) children();
module plates_on(sd) for (r = [1, 2, 3]) place(sd) {
  color([0.1, 0.1, 0.11]) plate_full(r, sd);
  if (sd == "wordmark") color([0.95, 0.75, 0.05]) translate([0, 0, T - ACC_D]) linear_extrude(ACC_D) chevrons2d(r);
  color([0.6, 0.6, 0.62]) for (b = bolts(r)) translate([b[0], b[1], T - (thumbs(r, sd) ? 0 : CB_H)]) cylinder(d = thumbs(r, sd) ? 11 : 9.5, h = thumbs(r, sd) ? 6 : 2.7);
}
module frame_ref() color([0.15, 0.15, 0.17]) {
  for (x = [0, FACE_L - RAIL], y = [0, DP - RAIL]) translate([x, y, 0]) cube([RAIL, RAIL, H_TOT]);
  for (z = RAIL_Z0, y = [0, DP - RAIL]) translate([0, y, z]) cube([FACE_L, RAIL, RAIL]);
  for (z = [RAIL_Z0[0], RAIL_Z0[3]], x = [0, FACE_L - RAIL]) translate([x, RAIL, z]) cube([RAIL, DP - 2 * RAIL, RAIL]);
}
module gussets_ref() color([0.2, 0.2, 0.22]) for (y = [-3.2, DP]) for (m = [0, 1]) translate([m * FACE_L, y + 3.2, 0]) mirror([m, 0, 0]) rotate([90, 0, 0]) linear_extrude(3.2) {
  polygon([[0, 0], [GUS_RL, 0], [GUS_RL, 20], [22, 60], [0, 60]]);
  for (z = [SLOT[1], SLOT[2]]) polygon([[0, z - 30], [20, z - 30], [GUS_RL, z - 10], [GUS_RL, z + 10], [20, z + 30], [0, z + 30]]);
  polygon([[0, H_TOT], [GUS_RL, H_TOT], [GUS_RL, H_TOT - 20], [22, H_TOT - 60], [0, H_TOT - 60]]);
}
module contents_ref() {          // EST from photos 47/48
  color([0.12, 0.3, 0.75]) translate([90, 60, 22]) cube([70, 139, 35]);                       // hub (row 1, left)
  color([0.1, 0.1, 0.11]) translate([205, 110, 25]) cube([40, 60, 60]);                      // printed node
  color([0.2, 0.2, 0.22]) translate([265, 90, 95]) cube([80, 70, 6]);                         // MTi plate
  color([0.08, 0.08, 0.09]) { translate([25, 75, 140]) cube([132, 106, 41]); translate([25, 75, 215]) cube([132, 106, 47]); }   // RTK/LTE + Orin, I/O at x 25
  color([0.92, 0.92, 0.9]) translate([300, 140, H_TOT + 8]) scale([1, 1, 0.35]) sphere(d = 140, $fn = 48);                        // dome
  color([0.18, 0.18, 0.2]) translate([FACE_L + 2, 80, 120]) cube([45, 110, 120]);                                              // V-mount battery (end)
}
module cage(sides = ["wordmark", "plain"]) { frame_ref(); gussets_ref(); contents_ref(); for (sd = sides) plates_on(sd); }
module exploded() {
  r = 2; sd = "wordmark";
  color([0.1, 0.1, 0.11]) { translate([-25, 0, 0]) half_of(r, sd, "L"); translate([25, 0, 0]) half_of(r, sd, "R"); }
  color([0.95, 0.75, 0.05]) for (m = [0, 1]) translate([m == 0 ? -25 : 25, 0, T + 20]) translate([m * W, 0, 0]) mirror([m, 0, 0]) chevron_part(r);
  color([0.35, 0.35, 0.38]) translate([0, 0, -30]) splice_bar(r);
  color([0.6, 0.6, 0.62]) translate([W / 2 - SPL[1] + 0.2, vb(r) + 6.5, T / 2 - SPL[0] / 2 + 40]) spline(r);
}

// ================================================================ MONOLITH (wordmark side): one plate deck -> top rail
function lsel(a, b) = layout == "twoline" ? a : b;
M_LET = lsel(L2_LETTERS, L1_LETTERS); M_LZ = lsel(L2_LINE_Z, L1_LINE_Z); M_SEAM = lsel(L2_SEAM, L1_SEAM);
M_BU = lsel(L2_BOLT_U, L1_BOLT_U); M_PEGS = lsel(L2_PEGS, L1_PEGS); M_PEG_OF = lsel(L2_PEG_OF, L1_PEG_OF);
M_CELLS = variant == "stencil" ? lsel(L2_CELLS_ST, L1_CELLS_ST) : lsel(L2_CELLS_AP, L1_CELLS_AP);
M_STATS = lsel(L2_STATS, L1_STATS); M_CAP = lsel(L2_CAP, L1_CAP);
EDGE_IN = 2.0; MZ0 = SLOT[0] - EDGE_IN; MZ1 = SLOT[3] + EDGE_IN;          // 279.38 tall: the deck / top bolts sit 2 inside the edges (U-break), fits the 281 bed
MHEX_AF = 3.2; MHEX_R = MHEX_AF / sqrt(3);                                 // micro-hex
M_BOLTS = [for (z = SLOT, u = M_BU) [u, z]];                              // 4 rows x 4 = 16
LET_T = 2.0; GAP = 2.5; PEG_D = 4.0; PEG_FIT = 0.2; BOSS_D = 7.0; PEG_IN = 3.0;   // applique letters: 2.0 thick on 2.5 standoff bosses -> 4.5 proud
function lz(i) = M_LZ[i];
function line_zr() = let(zs = [for (z = M_LZ) z]) [min([for (z = zs) z[0]]), max([for (z = zs) z[1]])];
// spline groove segments + rear splice bars: only in letter-free bands at the seam (never over a rail)
function lines_z() = layout == "twoline" ? [[min(lz(3)[0], lz(4)[0], lz(5)[0]), max(lz(3)[1], lz(4)[1], lz(5)[1])], [min(lz(0)[0], lz(1)[0], lz(2)[0]), max(lz(0)[1], lz(1)[1], lz(2)[1])]]
                                         : [line_zr()];
function groove_segs() = let(L = lines_z()) layout == "twoline" ? [[MZ0 + 6, L[0][0] - 3], [L[0][1] + 3, L[1][0] - 3], [L[1][1] + 3, MZ1 - 6]] : [[MZ0 + 6, L[0][0] - 3], [L[0][1] + 3, MZ1 - 6]];
function m_splices() = [[RAIL_Z0[3] - ROW_H[2] + 2, RAIL_Z0[3] - 2], [RAIL_Z0[0] + RAIL + 2, lines_z()[0][0] - 3]];   // row 3 bay ; row 1 below the lower line
function m_spl_ins(b) = let(h = b[1] - b[0]) h >= 24 ? [for (s = [-1, 1], t = [-1, 1]) [M_SEAM + s * INS_X, (b[0] + b[1]) / 2 + t * (h / 2 - 5)]] : [for (s = [-1, 1]) [M_SEAM + s * INS_X, (b[0] + b[1]) / 2]];
module mono_outline2d() polygon([[CORNER, MZ0], [W - CORNER, MZ0], [W, MZ0 + CORNER], [W, MZ1 - CORNER], [W - CORNER, MZ1], [CORNER, MZ1], [0, MZ1 - CORNER], [0, MZ0 + CORNER]]);
module mono_full(v) difference() {
  linear_extrude(T) mono_outline2d();
  for (c = (v == "stencil" ? lsel(L2_CELLS_ST, L1_CELLS_ST) : lsel(L2_CELLS_AP, L1_CELLS_AP))) translate([c[0], c[1], -1]) rotate([0, 0, 30]) cylinder(r = MHEX_R, h = T + 2, $fn = 6);
  if (v == "stencil") for (L = M_LET) {
    translate([0, 0, -1]) linear_extrude(T + 2) polygon(L);                                               // letters THROUGH (single outlines: nothing falls out)
    translate([0, 0, T - 0.8]) linear_extrude(1) offset(delta = 0.8) polygon(L);                          // 0.8 face bevel (stepped)
    translate([0, 0, T - 0.4]) linear_extrude(1) offset(delta = 1.2) polygon(L);
  }
  if (v == "applique") for (p = lsel(L2_PEGS, L1_PEGS)) translate([p[0], p[1], -1]) cylinder(d = PEG_D, h = T + 2);
  for (b = M_BOLTS) translate([b[0], b[1], 0]) {
    translate([0, 0, -1]) cylinder(d = M5B, h = T + 2);
    if (fix_mono == "ts") translate([0, 0, T - TS_SEAT[1]]) cylinder(d = TS_SEAT[0], h = 2); else translate([0, 0, T - CB_H]) cylinder(d = CB_D, h = CB_H + 1);
  }
  if (v == "stencil") translate([0, 0, T - ACC_D]) linear_extrude(ACC_D + 1) chevrons2d(3, ACC_CLR);       // the one yellow accent: row-3 chevrons
  for (g = groove_segs()) if (g[1] - g[0] > 8) translate([M_SEAM - SPL[1], g[0], T / 2 - SPL[0] / 2 - 0.1]) cube([2 * SPL[1], g[1] - g[0], SPL[0] + 0.2]);
  for (b = m_splices(), p = m_spl_ins(b)) translate([p[0], p[1], -0.01]) cylinder(d = INS3_D, h = INS3_DEP);
}
module mono_half(v, h) intersection() { mono_full(v); translate([h == "L" ? -1 : M_SEAM, MZ0 - 1, -1]) cube([h == "L" ? M_SEAM + 1 : W - M_SEAM + 1, MZ1 - MZ0 + 2, T + 2]); }
module mono_splice(b) difference() {
  translate([M_SEAM - SPLICE_HW, b[0], -SPLICE_T]) cube([2 * SPLICE_HW, b[1] - b[0], SPLICE_T]);
  for (p = m_spl_ins(b)) translate([p[0], p[1], -SPLICE_T - 1]) { cylinder(d = M3B, h = SPLICE_T + 2); cylinder(d = 6.2, h = 2.5); }
}
module letter_part(i) {                                     // use frame: underside on the plate face (z = T) + GAP
  translate([0, 0, T + GAP]) linear_extrude(LET_T) polygon(M_LET[i]);
  for (j = [0 : len(M_PEGS) - 1]) if (M_PEG_OF[j] == i) translate([M_PEGS[j][0], M_PEGS[j][1], 0]) {
    translate([0, 0, T]) cylinder(d = BOSS_D, h = GAP + 0.01);                                            // standoff boss (bears on the face)
    translate([0, 0, T - PEG_IN]) cylinder(d = PEG_D + PEG_FIT, h = PEG_IN + 0.01);                       // 0.2 press-fit peg
  }
}
module letter_print(i) let(L = M_LET[i], x0 = min([for (p = L) p[0]]), y0 = min([for (p = L) p[1]]))
  translate([-x0, -y0, T + GAP + LET_T]) mirror([0, 0, 1]) letter_part(i);                                  // letter face on the bed, bosses + pegs up
function lw(i) = max([for (p = M_LET[i]) p[0]]) - min([for (p = M_LET[i]) p[0]]);
function lh(i) = max([for (p = M_LET[i]) p[1]]) - min([for (p = M_LET[i]) p[1]]);
module letters_plate() {                                    // all six on one bed: two rows of three
  ord = [[1, 0, 5], [3, 2, 4]];
  for (r = [0, 1]) for (c = [0 : 2]) let(i = ord[r][c], xo = c == 0 ? 0 : c == 1 ? lw(ord[r][0]) + 6 : lw(ord[r][0]) + lw(ord[r][1]) + 12)
    translate([xo, r * (max(lh(1), lh(3)) + 8), 0]) letter_print(i);
}
module mono_on_cage(v) translate([X0, 0, 0]) rotate([90, 0, 0]) {
  color([0.1, 0.1, 0.11]) mono_full(v);
  if (v == "stencil") color([0.95, 0.75, 0.05]) translate([0, 0, T - ACC_D]) linear_extrude(ACC_D) chevrons2d(3);
  if (v == "applique") color([0.95, 0.75, 0.05]) for (i = [0 : 5]) letter_part(i);
  color([0.6, 0.6, 0.62]) for (b = M_BOLTS) translate([b[0], b[1], T - (fix_mono == "ts" ? 0 : CB_H)]) cylinder(d = fix_mono == "ts" ? 11 : 9.5, h = fix_mono == "ts" ? 6 : 2.7);
}
module interior_dark() color([0.04, 0.04, 0.05]) translate([25, 30, 5]) cube([FACE_L - 50, DP - 60, H_TOT - 10]);   // render only: the dark cage interior behind the stencil
module cage_mono(v) { frame_ref(); gussets_ref(); contents_ref(); interior_dark(); mono_on_cage(v); plates_on("plain"); }
echo(str("MONOLITH ", layout, " / ", variant, ": plate ", W, " x ", MZ1 - MZ0, " (deck-row bolts ", EDGE_IN, " inside the bottom edge, top-row ", EDGE_IN, " inside the top: deck / top rail overlap ",
         RAIL_Z0[0] + RAIL - MZ0, " / ", MZ1 - RAIL_Z0[3], ", rails 2/3 fully covered), halves ", M_SEAM, " + ", W - M_SEAM, " wide; cap height ", M_CAP,
         "; ", len(M_BOLTS), " x M5 (", fix_mono == "ts" ? "captive thumbscrews" : "BHCS", ") into 14122"));
echo(str("MONOLITH OPEN AREA: stencil hex ", M_STATS[0], " + letters ", M_STATS[1], " cm2, over the case fins ", M_STATS[2], " | applique micro-hex ", M_STATS[3],
         " cm2, over the case fins ", M_STATS[4], " effective (R4.2 >= 32)"));
assert(MZ1 - MZ0 <= 281, "monolith half taller than the bed");
assert(M_SEAM <= 281 && W - M_SEAM <= 281, "monolith half wider than the bed");
assert(RAIL_Z0[0] + RAIL - MZ0 >= 10 && MZ1 - RAIL_Z0[3] >= 10, "deck / top rail overlap < 10");

// ================================================================ CUTOUT (wordmark side, row 2): black CANARY plate + yellow vented backer
// The plate is 304.8 x 80.80 and sits INSIDE the 81.86 row-2 bay (0.53 to each rail), front face flush with the rail faces.
// Retention: +/-z the rails themselves; +/-y and +/-x four M4 through front + backer into heat-sets in four printed L-brackets,
// each bolted with one M5 into a DROP-IN T-nut in the bay-facing slot of rail 2 (bottom pair) or rail 3 (top pair).
function csel(a, b) = lettering == "native" ? a : b;
C_LET = csel(CN_LETTERS, CC_LETTERS); C_BR = csel(CN_BRIDGES, CC_BRIDGES); C_CB = csel(CN_CELLS_B, CC_CELLS_B); C_CF = csel(CN_CELLS_F, CC_CELLS_F);
C_STATS = csel(CN_STATS, CC_STATS); C_CAP = csel(CN_CAP, CC_CAP);
CF_T = 5.0; REB_D = 3.2; BK_T = 3.0; BK_CLR = 0.3; CO_GAP = (ROW_H[1] - CO_H) / 2;   // skin = CF_T - REB_D = 1.8 -> yellow face 1.8 behind the front face
M4B = 4.5; INS4_D = 5.6; INS4_DEP = 6.0; PEG = [3.0, 2.5]; CF_MAXSPAN = 2.0;
BR = [14, 3.5, 7.0, 18];                    // bracket: width x, foot thickness, tab thickness (y), tab height
CZ0 = bay(2)[0] + CO_GAP;                   // plate bottom (frame z)
module co_letters2d() difference() { union() for (L = C_LET) polygon(L[0], L[1]); for (b = C_BR) translate([b[0], b[1]]) square([b[2] - b[0], b[3] - b[1]]); }
module co_outline2d(d = 0) offset(delta = -d) polygon([[3, 0], [CO_W - 3, 0], [CO_W, 3], [CO_W, CO_H - 3], [CO_W - 3, CO_H], [3, CO_H], [0, CO_H - 3], [0, 3]]);
module co_front() difference() {             // w = 0 back, w = CF_T front face
  union() {
    linear_extrude(CF_T) co_outline2d();
  }
  translate([0, 0, -1]) linear_extrude(REB_D + 1) difference() { co_outline2d(CO_RIM); }                  // rear rebate for the backer
  translate([0, 0, -1]) linear_extrude(CF_T + 2) co_letters2d();                                             // CANARY through
  translate([0, 0, CF_T - 0.4]) linear_extrude(1) offset(delta = 0.4) co_letters2d();                        // 0.4 face break
  for (c = C_CF) translate([c[0], c[1], -1]) rotate([0, 0, 30]) cylinder(r = CO_FHEX[0] / sqrt(3), h = CF_T + 2, $fn = 6);
  for (b = CO_BOSS) translate([b[0], b[1], -1]) cylinder(d = M4B, h = CF_T + 2);
  if (co_fix == "ts") for (b = CO_BOSS) translate([b[0], b[1], CF_T - 0.8]) cylinder(d = 10, h = 1);
}
module co_pegs() for (p = CO_PEGS) translate([p[0], p[1], REB_D - PEG[1]]) cylinder(d = PEG[0], h = PEG[1] + 0.01);   // on the rebate floor, pointing back
module co_front_full() union() { co_front(); co_pegs(); }
module co_backer() difference() {            // sits in the rebate: front face at w = REB_D (against the skin), back at REB_D - BK_T
  translate([0, 0, REB_D - BK_T]) linear_extrude(BK_T) co_outline2d(CO_RIM + BK_CLR);
  for (c = C_CB) translate([c[0], c[1], -1]) rotate([0, 0, 30]) cylinder(r = CO_BHEX[0] / sqrt(3), h = CF_T + 2, $fn = 6);        // fine hex under the letters
  for (c = C_CF) translate([c[0], c[1], -1]) rotate([0, 0, 30]) cylinder(r = CO_FHEX[0] / sqrt(3) + 0.3, h = CF_T + 2, $fn = 6);  // field holes, aligned (+0.3)
  for (b = CO_BOSS) translate([b[0], b[1], -1]) cylinder(d = M4B, h = CF_T + 2);
  for (p = CO_PEGS) translate([p[0], p[1], -1]) cylinder(d = PEG[0] + 0.3, h = CF_T + 2);
}
// bracket in PLATE coords (w = 0 plate back; the rail spans w -15..5, its bay-face slot at w = -5): foot on the rail's bay face
// behind the plate, tab against the plate back carrying the M4 heat-set, M5 down into a drop-in T-nut; foot runs toward the plate centre
module co_bracket(b) let(bottom = b[1] < CO_H / 2, zf = bottom ? -CO_GAP : CO_H + CO_GAP, sx = b[0] < CO_W / 2 ? 1 : -1,
                         fx0 = sx > 0 ? b[0] - BR[0] / 2 : b[0] - BR[0] / 2 - 14, tz0 = bottom ? zf : b[1] - BR[3] / 2 - 2,
                         tz1 = bottom ? b[1] + BR[3] / 2 + 2 : zf) difference() {
  union() {
    translate([fx0, bottom ? zf : zf - BR[1], -15]) cube([BR[0] + 14, BR[1], 14.5]);                         // foot (w -15 .. -0.5)
    translate([b[0] - BR[0] / 2, tz0, -BR[2] - 0.5]) cube([BR[0], tz1 - tz0, BR[2]]);                         // tab (w -7.5 .. -0.5)
  }
  translate([b[0], b[1], -INS4_DEP - 0.5]) cylinder(d = INS4_D, h = INS4_DEP + 0.6);                          // M4 heat-set (from the plate side)
  translate([b[0] + sx * (BR[0] / 2 + 7), bottom ? zf - 1 : zf - BR[1] - 1, -5]) rotate([-90, 0, 0]) cylinder(d = M5B, h = BR[1] + 2);   // M5 -> drop-in T-nut
}
module co_on_cage(ex = 0) translate([X0, CF_T, CZ0]) rotate([90, 0, 0]) {
  color([0.1, 0.1, 0.11]) co_front_full();
  color([0.95, 0.75, 0.05]) translate([0, 0, -ex * 40]) co_backer();
  color([0.35, 0.35, 0.38]) translate([0, 0, -ex * 70]) for (b = CO_BOSS) co_bracket(b);
  color([0.6, 0.6, 0.62]) translate([0, 0, -ex * 70]) for (b = CO_BOSS) let(bt = b[1] < CO_H / 2, sx = b[0] < CO_W / 2 ? 1 : -1) translate([b[0] + sx * (BR[0] / 2 + 7), bt ? -CO_GAP + BR[1] : CO_H + CO_GAP - BR[1] - 2.7, -5]) rotate([-90, 0, 0]) cylinder(d = 9.5, h = 2.7);   // M5 heads
  color([0.6, 0.6, 0.62]) for (b = CO_BOSS) translate([b[0], b[1], CF_T + ex * 30]) cylinder(d = co_fix == "ts" ? 9 : 7.6, h = co_fix == "ts" ? 5 : 2.2);
}
module plates_on_co() let($co = true) for (r = [1, 3]) place("wordmark") {
  color([0.1, 0.1, 0.11]) plate_full(r, "wordmark");
  color([0.6, 0.6, 0.62]) for (b = bolts(r)) translate([b[0], b[1], T - (thumbs(r, "wordmark") ? 0 : CB_H)]) cylinder(d = thumbs(r, "wordmark") ? 11 : 9.5, h = thumbs(r, "wordmark") ? 6 : 2.7);
}
module cage_co() { frame_ref(); gussets_ref(); contents_ref(); interior_dark(); co_on_cage(); plates_on_co(); plates_on("plain"); }
echo(str("CUTOUT ", lettering, ": plate ", CO_W, " x ", CO_H, " in the ", ROW_H[1], " bay (", CO_GAP, " each rail); cap height ", C_CAP,
         "; skin ", CF_T - REB_D, " -> yellow face ", CF_T - REB_D, " behind the front | open: letters (through the backer's fine hex) ", C_STATS[0],
         " + black field ", C_STATS[1], " cm2, over the case fins ", C_STATS[2], " (R4.2 >= 32) | 4 x M4 into heat-set L-brackets on 4 x M5 drop-in T-nuts"));
echo(str("CUTOUT 45 deg on the bed: ", round((CO_W + CO_H) / sqrt(2) * 10) / 10, " square; + 2 x 3 brim = ", round(((CO_W + CO_H) / sqrt(2) + 6) * 10) / 10, " (<= 281); 6 mm brim -> ",
         round(((CO_W + CO_H) / sqrt(2) + 12) * 10) / 10));
assert((CO_W + CO_H) / sqrt(2) + 6 <= 281, "cutout plate does not fit at 45 deg with a 3 mm brim");
assert(CF_T - REB_D >= 1.5 && CF_T - REB_D <= 2.0, "yellow face must sit 1.5-2 behind the front face");
assert(CO_GAP > 0.3, "plate does not clear the rails");
// ---------------------------------------------------------------- exports
if (view == "cage_wm" || view == "cage_plain" || view == "cage34") { if (format == "monolith") cage_mono(variant); else if (format == "cutout") cage_co(); else cage(); }
if (view == "co_exploded") co_on_cage(1);
if (view == "co_detail") intersection() { co_on_cage(); translate([X0 + 150, -30, CZ0 - 5]) cube([90, 60, 95]); }
if (view == "mono_pair") { cage_mono("stencil"); translate([FACE_L + 110, 0, 0]) cage_mono("applique"); }
if (view == "mono_exploded") { color([0.1, 0.1, 0.11]) { translate([-20, 0, 0]) mono_half(variant, "L"); translate([20, 0, 0]) mono_half(variant, "R"); }
  if (variant == "applique") color([0.95, 0.75, 0.05]) for (i = [0 : 5]) translate([0, 0, 25]) letter_part(i);
  color([0.35, 0.35, 0.38]) for (b = m_splices()) translate([0, 0, -25]) mono_splice(b); }
if (view == "exploded") exploded();
if (view == "none") {
  if (part == "plate" && half != "full") let(x0 = half == "L" ? 0 : -W / 2) translate([x0, vb(row) + EAR_OV + 2, T]) rotate([180, 0, 0]) half_of(row, side, half);   // FACE DOWN
  if (part == "plate" && half == "full") { assert(row == 3, "only row 3 fits the bed whole (45 deg)");
    rotate([0, 0, 45]) translate([-W / 2, -(vb(3) + vt(3)) / 2, T]) rotate([180, 0, 0]) plate_full(3, side); }
  if (part == "splice") translate([0, 0, SPLICE_T]) rotate([180, 0, 0]) splice_bar(row);
  if (part == "spline") spline(row);
  if (part == "chevron") chevron_part(row);
  if (part == "mono") let(x0 = half == "L" ? 0 : -M_SEAM) translate([x0, -MZ0, T]) rotate([180, 0, 0]) translate([0, 0, 0]) mono_half(variant, half);   // FACE DOWN
  if (part == "mono_splice") for (i = [0, 1]) translate([i * 40, 0, SPLICE_T]) rotate([180, 0, 0]) translate([-M_SEAM, -m_splices()[i][0], 0]) mono_splice(m_splices()[i]);
  if (part == "mono_spline") for (i = [0 : len(groove_segs()) - 1]) let(g = groove_segs()[i]) if (g[1] - g[0] > 8) translate([i * 8, 0, 0]) cube([2 * SPL[1] - 0.4, g[1] - g[0] - 1, SPL[0]]);
  if (part == "letter") letter_print(let_i);
  if (part == "letters_plate") letters_plate();
  if (part == "mono_chevron") chevron_part(3);
  if (part == "co_front") rotate([0, 0, 45]) translate([-CO_W / 2, -CO_H / 2, CF_T]) mirror([0, 0, 1]) co_front_full();     // FACE DOWN, 45 deg
  if (part == "co_backer") rotate([0, 0, 45]) translate([-CO_W / 2, -CO_H / 2, REB_D]) mirror([0, 0, 1]) co_backer();      // yellow face down, 45 deg
  if (part == "co_brackets") for (i = [0 : 3]) let(b = CO_BOSS[i]) translate([i * 45, 0, b[0] + 21]) rotate([0, 90, 0]) translate([0, -b[1], 0]) co_bracket(b);   // L profile on the bed
  if (part == "co_row") let($co = true) let(x0 = half == "L" ? 0 : -W / 2) translate([x0, vb(row) + 2, T]) rotate([180, 0, 0]) half_of(row, "wordmark", half);
}
